SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_item_virtual;

CREATE TABLE /*TABLE_PREFIX*/t_item_virtual (
  pk_i_id INT NOT NULL AUTO_INCREMENT,
  fk_i_item_id INT(11) UNSIGNED NOT NULL,
  i_version INT DEFAULT 1,
  i_status INT(11) DEFAULT 0,
  i_download INT(11) DEFAULT 0,
  s_file VARCHAR(500) DEFAULT NULL,
  s_comment VARCHAR(500) NOT NULL,
  dt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (pk_i_id),
  FOREIGN KEY (fk_i_item_id) REFERENCES /*TABLE_PREFIX*/t_item (pk_i_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';


SET FOREIGN_KEY_CHECKS=1;