name: Download from FTP and Commit to GitHub

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Files from FTP
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        mkdir -p ftp_files
        lftp -c "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp://ftp.yourserver.com && mirror --verbose /remote/path ./ftp_files"

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add ftp_files
        git commit -m "Downloaded files from FTP"
        git push
